"""create db tables

Revision ID: 0434dbc28b24
Revises: e6f7a8b9c0d1
Create Date: 2026-08-23 20:45:51.240432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0434dbc28b24'
down_revision: Union[str, Sequence[str], None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_chunks_embedding_hnsw'), table_name='memory_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_memory_chunks_org_source'), table_name='memory_chunks')
    op.drop_constraint(op.f('uq_pending_users_email'), 'pending_users', type_='unique')
    op.drop_constraint(op.f('uq_pending_users_org_slug'), 'pending_users', type_='unique')
    op.drop_constraint(op.f('uq_pending_users_verification_token_hash'), 'pending_users', type_='unique')
    op.drop_index(op.f('ix_pending_users_email'), table_name='pending_users')
    op.create_index(op.f('ix_pending_users_email'), 'pending_users', ['email'], unique=True)
    op.drop_index(op.f('ix_pending_users_org_slug'), table_name='pending_users')
    op.create_index(op.f('ix_pending_users_org_slug'), 'pending_users', ['org_slug'], unique=True)
    op.drop_index(op.f('ix_pending_users_verification_token_hash'), table_name='pending_users')
    op.create_index(op.f('ix_pending_users_verification_token_hash'), 'pending_users', ['verification_token_hash'], unique=True)
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=False)
    op.drop_index(op.f('ix_pending_users_verification_token_hash'), table_name='pending_users')
    op.create_index(op.f('ix_pending_users_verification_token_hash'), 'pending_users', ['verification_token_hash'], unique=False)
    op.drop_index(op.f('ix_pending_users_org_slug'), table_name='pending_users')
    op.create_index(op.f('ix_pending_users_org_slug'), 'pending_users', ['org_slug'], unique=False)
    op.drop_index(op.f('ix_pending_users_email'), table_name='pending_users')
    op.create_index(op.f('ix_pending_users_email'), 'pending_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_pending_users_verification_token_hash'), 'pending_users', ['verification_token_hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_pending_users_org_slug'), 'pending_users', ['org_slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_pending_users_email'), 'pending_users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_memory_chunks_org_source'), 'memory_chunks', ['org_id', 'source_type'], unique=False)
    op.create_index(op.f('ix_memory_chunks_embedding_hnsw'), 'memory_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
