"""create db tables

Revision ID: 7e3c66818275
Revises: 0434dbc28b24
Create Date: 2026-08-23 20:46:14.733898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e3c66818275'
down_revision: Union[str, Sequence[str], None] = '0434dbc28b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
